### ISSUE TITLE
Write advanced section on Windows, and what the issues are

### ISSUE THREAD

**Issue by jkhartshorne** [pushkin-consortium/pushkin#154]
- And in particular that you can have a site with authentication, but you just won't be able to test it "locally".

**Comment by parkerrobbins** [comment]
I actually think, by the way, that it may be possible to run Pushkin using the Windows Subsystem for Linux with the basic template because the original bug had to do with port forwarding and the browser not accepting a site using auth0 without an SSL certificate.

**Comment by jkhartshorne** [comment]
Worth checking, then!

**Comment by jkhartshorne** [comment]
I had thought the problem was different. Please check that out.

**Comment by parkerrobbins** [comment]
You might be thinking of the problem I had running WSL 2 in a virtual machine. That was actually a separate thing not relevant to actual Windows users. So we'll have to have @restmegan give this another go using WSL.

**Comment by jkhartshorne** [comment]
Sounds good!

**Comment by parkerrobbins** [comment]
Closed via #167 and #168:
- No need to explain the idiosyncrasies of Windows in an Advanced section because the bug in WSL was fixed and it now behaves the way we want on Windows (both local and AWS deploy for both site templates work). 
- Updated installation instructions instead, keeping EC2 instructions but highlighting the limitations of this method.
