### ISSUE TITLE
Security concern with putting salt in a YAML file

### ISSUE THREAD

**Issue by suchow** [pushkin-consortium/pushkin#215]
The documentation and CLI tool generate a YAML file that includes a key `salt` that the documentation says is used to encrypt private information. Placing this key in a YAML file with other configuration settings is a security concern because it will likely lead developers to leak the keys by checking the file into public repositories.

**Comment by jkhartshorne** [comment]
That yaml file is .gitignored because it ultimately has a number of
passwords. But do you suggest something else?

On June 26, 2023, Sebastian Waz ***@***.***> wrote:
> The documentation and CLI tool generate a YAML file that includes a
> key salt that the documentation says is used to encrypt private
> information. Placing this key in a YAML file with other configuration
> settings is a security concern because it will likely lead developers
> to leak the keys by checking the file into public repositories.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/pushkin-consortium/pushkin/issues/215>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/ABOVVY67YSS5X22GIVBR273XNHYNLANCNFSM6AAAAAAZUVVDBI>.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>


--
Sent with HEY <https://hey.com/sent>

**Comment by suchow** [comment]
👍 , my bad
