### ISSUE TITLE
Install site template from github URL

### ISSUE THREAD

**Issue by jkhartshorne** [pushkin-consortium/pushkin#222]
Currently we can install from the official list of templates OR from a local path. Use a URL to a github version.

**Comment by jkhartshorne** [comment]
Notes:
- There is a JSON file in the CLI that lists official site templates and URLs.
- The CLI reads from that list and presents each official site as an option, plus an option for 'path'. If a user selects one of the official sites, it just looks up the URL and runs the install.
- All that's needed here is to add an option 'url' and use that URL for the installation command. 

Note that the URL is not for the github repo. When someone publishes a named version of a github repo, they have the option of including binaries such as a .zip file. When we publish the official site templates, we include just such a .zip file, always called `Archive.zip`. The URL for that file is what we want.

**Comment by jkhartshorne** [comment]
For the released version, see this example: https://github.com/pushkin-consortium/pushkin-sitetemplate-basic/releases

**Comment by jessestorbeck** [comment]
Some notes on what I've figured out so far:
- Running `install site` calls `handleInstall` in src/index.js. Most of the action seems to be in `handleInstall`.
- When you choose a site template (not 'path'), it extracts an object listing all versions from a URL (e.g. https://api.github.com/repos/pushkin-consortium/pushkin-sitetemplate-basic/releases). The keys are the tag_name for each version (e.g. 'v0.2.0') and the values are the url for each version (e.g. https://api.github.com/repos/pushkin-consortium/pushkin-sitetemplate-basic/releases/112580547). This is specified in the `getVersions` function in src/index.js.
- Once you have the url for the version you want, `getPushkinSite` (in src/commands/sites/index.js) extracts the browser_download_url from the object at the version url. browser_download_url targets the Archive.zip file.

Thus it seems like there are a few possible ways of adding a URL option to `install site`:
1. Make a new function `getPushkinSiteFromURL` which is substantially similar to `getPushkinSite` but instead of taking the release URL as its argument, it takes the url pointing directly to the Archive.zip file. This is not ideal since it repeats most of `getPushkinSite`.
2. Add a conditional to `getPushkinSite` such that if the url argument ends in 'Archive.zip', it downloads directly from there. This seems like the best option, but maybe adding regex to detect an Archive.zip file is a little hacky? Or maybe there's a function to detect whether the argument is a zip file. I suppose you could also try to condition on whether 'url' was chosen inside `handleInstall`, but I'm imagining there could be a scope issue with this.
3. Add something to `handleInstall` so that it takes the Archive.zip url and goes backwards to the release version url. Then `getPushkinSite` could be called as normal. This seems circuitous/inefficient.

**Comment by jkhartshorne** [comment]
We agreed on (2).

**Comment by jessestorbeck** [comment]
Basically (2) was the approach, but we decided to ask for the URL to the template releases (e.g. https://api.github.com/repos/pushkin-consortium/pushkin-sitetemplate-basic/releases OR https://github.com/pushkin-consortium/pushkin-sitetemplate-basic/releases). This way, no changes to `getPushkinSite` are needed. The user is still asked which version of the template they want to use, just like if they wanted to use one of the official templates. Only `handleInstall` needed to be modified.
