### ISSUE TITLE
Not sure process.env.PUBLIC_URL is still used

### ISSUE THREAD

**Issue by jkhartshorne** [pushkin-consortium/pushkin#236]
Noticed this when I was reviewing [this commit](https://github.com/pushkin-consortium/pushkin/pull/235/commits/7af72a1851a88d927fa22bee9da41bb844c4cc20). I think this may be from an older version of create-react-app. Not of the current code seems to use it.

**Comment by hunterschep** [comment]
I think [this page](https://create-react-app.dev/docs/using-the-public-folder/#adding-assets-outside-of-the-module-system) in the react docs is most related to this. According to [this](https://create-react-app.dev/docs/using-the-public-folder/#adding-assets-outside-of-the-module-system), it is still supported in scripts 0.5.0 or higher 

They also issue some guidance on the usage of the PUBLIC_URL and folder as opposed to importing things normally

**Downsides of using the `public` folder**:
- Files aren't minified or post-processed.
- Missing files won't show errors until runtime, leading to 404s for users.
- Filenames lack content hashes, requiring manual updates or query arguments when changed.

**When to use the `public` folder**:
- Specific filenames are required in the build, like `manifest.webmanifest`.
- Dynamic references are needed for a vast number of images.
- Small scripts, like `pace.js`, need to be outside the bundled code.
- Certain libraries clash with webpack and must be added via `<script>` tags.

**Comment by hunterschep** [comment]
See above comment, usage of this feature makes sense for the scope of our project

**Comment by jessestorbeck** [comment]
I actually found a page in our docs explaining why we use the public folder for image/video stimuli: https://languagelearninglab.gitbook.io/pushkin/advanced/experiment-structure/experiment-web-page-component#assets

Incidentally, I missed updating this page based on https://github.com/pushkin-consortium/pushkin-client/pull/39. Updating it now.

Perhaps though someone ought to check where exactly images used in a jsPsych timeline should go, since these two pages in our docs are actually at odds with respect to where one should put them in their Pushkin site: [in the experiment's `web page/src/assets` folder](https://languagelearninglab.gitbook.io/pushkin/advanced/modifying-experiment-templates#adding-static-assets) or [the site's `pushkin/front-end/public` folder](https://languagelearninglab.gitbook.io/pushkin/advanced/experiment-structure/experiment-web-page-component#assets)

This could probably be added to the list of "easy" tasks we talked about yesterday. @hunterschep or @ayang21, let me know if you want to test this, otherwise I'll do it.

**Comment by jessestorbeck** [comment]
I've tested this now with images in both `experiments/[exp]/web page/src/assets` and `pushkin/front-end/public`. My timeline looks like this:
```javascript
    const timeline = []

    var trial1 = {
        type: jsPsychImageKeyboardResponse,
        stimulus: process.env.PUBLIC_URL + '/patrick1.svg',
        choices: ['s', 'p'],
        prompt: "<p>Press 's' for Spongebob. Press 'p' for Patrick.</p>",
    }
    timeline.push(trial1);
  
    var trial2 = {
        type: jsPsychImageKeyboardResponse,
        stimulus: process.env.PUBLIC_URL + '/spongebob1.svg',
        choices: ['s', 'p'],
        prompt: "<p>Press 's' for Spongebob. Press 'p' for Patrick.</p>",
    }
    timeline.push(trial2);

    var trial3 = {
        type: jsPsychImageKeyboardResponse,
        stimulus: process.env.PUBLIC_URL + '/patrick2.svg',
        choices: ['s', 'p'],
        prompt: "<p>Press 's' for Spongebob. Press 'p' for Patrick.</p>",
    }
    timeline.push(trial3);
  
    var trial4 = {
        type: jsPsychImageKeyboardResponse,
        stimulus: process.env.PUBLIC_URL + '/spongebob2.svg',
        choices: ['s', 'p'],
        prompt: "<p>Press 's' for Spongebob. Press 'p' for Patrick.</p>",
    }
    timeline.push(trial4);
```
Images in the experiment's assets folder are **not** available within the jsPsych timeline:
<img width="1312" alt="Screen Shot 2023-10-23 at 1 48 14 PM" src="https://github.com/pushkin-consortium/pushkin/assets/126021561/5babff0b-4421-4eb0-94c9-355f7a1d22f1">
Images in the site's public folder **are** available within the jsPsych timeline:
<img width="1312" alt="Screen Shot 2023-10-23 at 1 48 41 PM" src="https://github.com/pushkin-consortium/pushkin/assets/126021561/4a37b569-1ebb-48ad-b2e4-f4f569b9ba89">
I guess the good news is we have one way that works for including image/video stimuli in an experiment, although I think requiring image/video stimuli to go in the site's public folder is not ideal for a few reasons:
- It seems like it violates Pushkin's design goal of having all the files for a particular experiment in one place.
- We can't develop experiment templates with image/video stimuli, since the files would need to go outside the template itself

It might be nice if `prep` did move files from the experiment's assets folder to the public folder, as [this page](https://languagelearninglab.gitbook.io/pushkin/advanced/modifying-experiment-templates#adding-static-assets) in the docs currently states.

**Comment by jkhartshorne** [comment]
> It might be nice if prep did move files from the experiment's assets folder to the public folder, as [this page](https://languagelearninglab.gitbook.io/pushkin/advanced/modifying-experiment-templates#adding-static-assets) in the docs currently states.

I think that's right. But you have to be careful with name spaces. (What happens if two files have the same name?) So I'd try to use subfolders within the public folder.

**Comment by jessestorbeck** [comment]
Addressed by https://github.com/pushkin-consortium/pushkin-cli/pull/121 [d49810d](https://github.com/pushkin-consortium/pushkin-cli/pull/121/commits/d49810d9741b0106c2c138f7f86f6d3e3b0a0bf0)
