### ISSUE TITLE
stale branch updates2023

### ISSUE THREAD

**Issue by jkhartshorne** [pushkin-consortium/pushkin#320]
@hunterschep is there anything in the unmerged commits to [updates2023](https://github.com/pushkin-consortium/pushkin/tree/updates2023) that is needed? If not, can you suppress that branch? I'm not sure of the best procedure, but maybe just hard delete those commits and then it should be up to date.

**Comment by hunterschep** [comment]
Since the [updates2023](https://github.com/pushkin-consortium/pushkin/tree/updates2023) branch was from the pre-monorepo and mkdocs era, I don't think anything in that branch is necessary, it can probably be deleted and or rebased. 

I don't just removing any extra commits would make it up to date as it does not reflect the monorepo structure, I think it could probably just be deleted as we have not used it since doing the reorganization push. @jessestorbeck do you have an opinion on this?

**Comment by jessestorbeck** [comment]
updates2023 didn't have anything in it that needed to be merged, so I deleted the branch. Branches can be deleted [here](https://github.com/pushkin-consortium/pushkin/branches) or on the page for their particular PR after they're merged. They can be restored if needed as well. I agree we could definitely clean out some additional old branches.
