### ISSUE TITLE
Quickstart: Clarifications about directory structure and config file needed under Making an Experiment

### ISSUE THREAD

**Issue by parkerrobbins** [pushkin-consortium/pushkin#37]
I'm finding the first sentence a bit vague and don't really understand the meaning.

> Each folder in here contains something unique to each experiment. 

I feel like the database aspect gets glossed over a bit in the quickstart. For example, the following sentence:

> There’s also a configuration file that allows us to define a full name for the experiment and specify what database to use, among other things.

Why might one want to specify a database to use? Why is it important to define a full name for the experiment?

**Comment by conbainbridge** [comment]
1.) The sentence I believe is simply meant to note that each experiment will have it's own copy of a self contained folder structure with files that are specific to the experiment.
2.) Yeah...the database stuff is glossed over I believe because this aspect is the part that still has work to be done to sort out the structure/functionality
3.) It is initialized to a test db, but one might want to have each experiment's data live in its own database I suppose.
4.) Defining the full name for the experiment will be the name that shows on the QuizTile on the homepage. The short name is for the url/routing.
